name: Private Node Deployment

run-name: deploy contracts to aws hardhat dev env

on:
  push:
    branches:
      - deployment/private-node
  workflow_dispatch:

jobs:
  deploy-aws:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Set up Doppler
        uses: dopplerhq/cli-action@v1

      - name: Build the project
        run: npm install

      # - name: Test the project
      #   run: npm run test
      #   env:
      #     DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

      - name: Copy files into EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HARDHAT_HOST }}
          username: ${{ secrets.AWS_HARDHAT_USERNAME }}
          key: ${{ secrets.AWS_HARDHAT_KEY }}
          source: "."
          target: "/home/lexer-contracts"
          rm: true

      - name: Deploy contracts to private testnet
        run: |
          cd "/home/lexer-contracts"
          npm run start-hardhat-node
          npm run deploy:local
